name: ltm
channels:
  - defaults
  - conda-forge
dependencies:
  - ipykernel
  - numpy
  - pandas
  - rasterio
  - matplotlib
  - pyproj
  - proj-data
  - varname
  - scipy
  - scikit-image
  - scikit-learn
  - jupyterlab
  - geopandas
  - coverage
  - earthengine-api
  - folium
  - seaborn
  - dask
  - pip
  - pip:
    - scikit-elm
