name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Ruff
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
  
  unittest:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Create and activate virtual environment
        run: python -m venv .venv
      - name: Install uv
        run: pip install uv
      - name: Verify uv installation
        run: uv --version
      - name: Build package
        run: |
          source .venv/bin/activate
          uv pip install poetry
          python -m poetry build
      - name: Install package
        run: uv pip install dist/slc-1.0.0-py3-none-any.whl
      - name: Install ruff and pylint
        run: uv pip install pytest
      - name: Run Tests
        run: source .venv/bin/activate && python -m pytest
